//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_placementTool p_placementTool;
        
        private static SteamVR_Input_ActionSet_general p_general;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_placementTool placementTool
        {
            get
            {
                return SteamVR_Actions.p_placementTool.GetCopy<SteamVR_Input_ActionSet_placementTool>();
            }
        }
        
        public static SteamVR_Input_ActionSet_general general
        {
            get
            {
                return SteamVR_Actions.p_general.GetCopy<SteamVR_Input_ActionSet_general>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_placementTool = ((SteamVR_Input_ActionSet_placementTool)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_placementTool>("/actions/placementTool")));
            SteamVR_Actions.p_general = ((SteamVR_Input_ActionSet_general)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_general>("/actions/general")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.placementTool,
                    SteamVR_Actions.general};
        }
    }
}
